### ISSUE TITLE
Add columns to the Results_MCMC file

### ISSUE THREAD

**Issue by Felipemendezrios** [BaM-tools/BaM#5]
Add two columns to the Results_MCMC file, one of them will be LogPrior and the other LogLikelihood in order to estimate the DIC selection criteria.

**Comment by benRenard** [comment]
Done! 1c22189af4cd00d0e8267c2b95e22c38ac56a517
But not exactly as requested: Results_MCMC is untouched to ensure back-compatibility.
Instead the implemented behavior is as follows:
1. DIC computation is performed after MCMC cooking, as part of the "MCMC summary" step
2. Two additional lines can be written in Config_Summary to specify (i) the file where DICs are stored, and (ii) the file where extended MCMC samples are written (extended = with additional columns for prior, hyper, lkh and deviance). See example [here](https://github.com/BaM-tools/BaM/blob/main/makefile/TEST_BaRatin/Config_Summary.txt). 
3. If the lines above are not specified, DIC is not computed (=> identical to previous behavior)
4. If you prefer not writing the extended MCMC file, use an empty string (or a blank line)


DIC is tricky as several versions exist in the literature. The code has been commented as shown below to clarify what is computed.

------

The DIC is based on the deviance $D(\theta) = -2log(p(x|\theta))$ and a penalization using the effective number of parameters $p_D$:

$DIC = D(\hat{\theta}) + 2p_D$

The maxpost is used for $\hat{\theta}$ in this subroutine, because it belongs to the MCMC sample and is hence necessarily feasible. Note that it is more common in the statistical literature to use the posterior mean, but as discussed by the DIC creators (Spiegelhalter et al.  2002) this is just a choice.

Three versions of the DIC are provided:
1. $DIC_1$ is the original version of Spiegelhalter (2002), based on the posterior MEAN of deviance $D(\theta)$. 
    $DIC_1 = D(\hat{\theta}) + 2( E[D(\theta)] - D(\hat{\theta}) )$
2. DIC2 is the alternative definition mentionned in Gelman (2014) and Spiegelhalter (2014), based on the posterior VARIANCE of $D(\theta)$.
    $DIC_2 = D(\hat{\theta}) + 2( \frac{1}{2} Var[D(\theta)] )$
3. $DIC_3$  is a third option used in Pooley and Marion (2018), based on both the posterior MEAN and VARIANCE of $D(\theta)$. Unlike $DIC_1$ and $DIC_2$, it does not use the deviance $D(\hat{\theta})$ computed at point-estimate $\hat{\theta}$, and therefore avoids having to make a choice for $\hat{\theta}$ (posterior mode, mean, median etc.).
    $DIC_3 =  E[D(\theta)] + \frac{1}{2} Var[D(\theta)] = \frac{1}{2} (DIC_1 + DIC_2)$

------

References

* Spiegelhalter, D.J., Best, N.G., Carlin, B.P., van der Linde, A.: Bayesian measures of model complexity and fit (with discussion). J. R. Stat. Soc. B (2002).
* Gelman, A., Hwang, J. & Vehtari, A. Understanding predictive information criteria for Bayesian models. Stat Comput 24, 997–1016 (2014). https://doi.org/10.1007/s11222-013-9416-2
* Spiegelhalter, D.J., Best, N.G., Carlin, B.P. and van der Linde, A. The deviance information criterion: 12 years on. J. R. Stat. Soc. B (2014), https://doi.org/10.1111/rssb.12062
* Pooley, C. M., & Marion, G. Bayesian model evidence as a practical alternative to deviance information criterion. Royal Society Open Science (2018), https://doi.org/10.1098/rsos.171519

**Comment by Felipemendezrios** [comment]
Even if three options are available, we should choose one to quantify DIC. I've chosen DIC2 for RatingShiftHappens, Do you agree @benRenard ?
